apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-deployment.yaml
      - ./infra/k8s/auth-postgres-statefulset.yaml
      - ./infra/k8s/auth-postgres-service.yaml
      - ./infra/k8s/events-deployment.yaml
      - ./infra/k8s/events-postgres-statefulset.yaml
      - ./infra/k8s/events-postgres-service.yaml
      - ./infra/k8s/chat-deployment.yaml
      - ./infra/k8s/chat-postgres-statefulset.yaml
      - ./infra/k8s/chat-postgres-service.yaml
      - ./infra/k8s/client-deployment.yaml
      - ./infra/k8s/ingress-srv.yaml
build:
  local:
    push: false
  artifacts:
    - image: dyahraus/auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: dyahraus/events-service
      context: events
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: dyahraus/chat-service
      context: chat
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: dyahraus/client-service
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.js'
            dest: .
          - src: 'src/***/*.css' # Add this line to sync CSS files
            dest: .
