apiVersion: skaffold/v2alpha3
kind: Config

build:
  local:
    push: true # IMPORTANT: Push to GCR
  artifacts:
    - image: gcr.io/lively-folder-450800-h3/auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/**.ts'
            dest: .

    - image: gcr.io/lively-folder-450800-h3/events-service
      context: events
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/**.ts'
            dest: .

    - image: gcr.io/lively-folder-450800-h3/chat-service
      context: chat
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/**.ts'
            dest: .

    - image: gcr.io/lively-folder-450800-h3/client-service
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/**.js'
            dest: .
          - src: 'src/***/**.css'
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-deployment.yaml
      - ./infra/k8s/auth-postgres-statefulset.yaml
      - ./infra/k8s/auth-postgres-service.yaml
      - ./infra/k8s/events-deployment.yaml
      - ./infra/k8s/events-postgres-statefulset.yaml
      - ./infra/k8s/events-postgres-service.yaml
      - ./infra/k8s/chat-deployment.yaml
      - ./infra/k8s/chat-postgres-statefulset.yaml
      - ./infra/k8s/chat-postgres-service.yaml
      - ./infra/k8s/client-deployment.yaml
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/managed-cert.yaml
