apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: dyahraus/auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: dyahraus/events-service
      context: events
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: dyahraus/client-service
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.js'
            dest: .
          - src: 'src/***/*.css' # Add this line to sync CSS files
            dest: .
