apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1 # You can scale this up later
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: dyahraus/auth-service
          # ports:
          #   - containerPort: 3001
          env:
            - name: PG_USER
              value: 'postgres'
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: PG_PASSWORD
            - name: PG_HOST
              value: auth-postgres-service # Connects to the Postgres service in the cluster
            - name: PG_PORT
              value: '5432'
            - name: PG_DATABASE
              value: 'rallyvite_auth'
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sg-api-key
                  key: SENDGRID_API_KEY
            - name: SENDER_EMAIL
              value: 'hey@rallyvite.com'
            - name: FRONTEND_URL
              value: 'https://rallyvite.com'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: rallyvitejwt-secret
                  key: JWT_KEY
            - name: KAFKA_BROKERS
              value: 'kafka-service:9092'
            - name: KAFKA_CLIENT_ID
              value: 'auth-service'
            - name: KAFKA_GROUP_ID
              value: 'auth-group'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: auth-service
      protocol: TCP
      port: 3000
      targetPort: 3000
