apiVersion: v1
kind: Service
metadata:
  name: chat-postgres-service
  namespace: rallyvite-prod
spec:
  selector:
    app: postgres-chat
  ports:
    - name: chat
      protocol: TCP
      port: 5432
      targetPort: 5432
