apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: events-service # Replace with your actual Docker image for the events service
          env:
            - name: PG_USER
              value: 'postgres'
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: PG_PASSWORD
            - name: PG_HOST
              value: 'events-postgres-service' # The Postgres service in the cluster
            - name: PG_PORT
              value: '5432'
            - name: PG_DATABASE
              value: 'rallyvite_events' # The database for the events service
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: rallyvitejwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
spec:
  selector:
    app: events-service
  ports:
    - name: events
      protocol: TCP
      port: 5000
      targetPort: 5000
