apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.0
          ports:
            - containerPort: 9092
              name: kafka-port
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper-service:2181'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://kafka-service:9092'
            - name: KAFKA_LISTENERS
              value: 'PLAINTEXT://0.0.0.0:9092'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_LOG_DIRS
              value: '/var/lib/kafka/data'
            - name: KAFKA_LOG_RETENTION_HOURS
              value: '168'
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: '300000'
            - name: KAFKA_HEAP_OPTS
              value: '-Xmx512M -Xms256M'
            - name: KAFKA_NUM_PARTITIONS
              value: '1'
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: '1'
            - name: KAFKA_LOG_FLUSH_INTERVAL_MESSAGES
              value: '10000'
            - name: KAFKA_LOG_FLUSH_INTERVAL_MS
              value: '1000'
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: '0'
            - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
              value: '1'
            - name: KAFKA_OFFSETS_RETENTION_MINUTES
              value: '10080'
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'
            - name: KAFKA_LOG_RETENTION_BYTES
              value: '-1'
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: '1073741824'
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: '300000'
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: '6000'
            - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: '6000'
            - name: KAFKA_INITIAL_BROKER_REGISTRATION_TIMEOUT_MS
              value: '60000'
            - name: KAFKA_BROKER_RACK
              value: 'rack-1'
            - name: KAFKA_CONTROLLED_SHUTDOWN_ENABLE
              value: 'true'
            - name: KAFKA_CONTROLLED_SHUTDOWN_MAX_RETRIES
              value: '3'
            - name: KAFKA_CONTROLLED_SHUTDOWN_RETRY_BACKOFF_MS
              value: '5000'
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  echo "Waiting for Zookeeper to be ready..."
                  while ! kafka-topics --zookeeper zookeeper-service:2181 --list; do
                    echo "Waiting for Zookeeper..."
                    sleep 1
                  done
                  echo "Zookeeper is ready!"
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 6
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
