apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration
          image: your-app-image
          env:
            - name: PG_USER
              value: 'postgres'
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: PG_PASSWORD
            - name: PG_HOST
              value: 'localhost'
            - name: PG_PORT
              value: '5432'
            - name: PG_DATABASE
              value: 'rallyvite_auth'
          command: ['node', 'runMigrations.js'] # Replace with the appropriate migration command
      restartPolicy: Never
